version: '3.5'

services:
  fluent-bit:
    image: ${IMAGE_NAME:-fluent/fluent-bit}:${IMAGE_TAG:-latest}
    networks:
      - log-net
    ports:
      - target: ${PORT}
        published: ${PORT}
        mode: host
    configs:
      - source: fluent-bit-conf
        target: /fluent-bit/etc/fluent-bit.conf
    logging:
      driver: json-file
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-1s}
      update_config:
        delay: ${UPDATE_DELAY:-10s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  log-net:
    name: ${LOG_NET_NAME:-log-net}
    driver: ${LOG_NET_DRIVER:-overlay}
    attachable: ${LOG_NET_ATTACHABLE:-true}

configs:
  fluent-bit-conf:
    name: ${FLUENT_BIT_CONF_NAME:-fluent-bit-conf}
    file: ./conf/fluent-bit.conf
